import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import React from "react";
import {ThemeProvider} from "@/app/theme-provider";
import StoreProvider from "@/app/StoreProvider";
import {AppProvider} from "@/context/AppContext";
import {Toaster} from 'react-hot-toast';

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "S Tech - business platform",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <head>
            <link rel="icon" href="/favicon.ico" sizes="any"/>
            <link
                rel="apple-touch-icon"
                href="/apple-touch-icon.png?<generated>"
                type="image/<generated>"
                sizes="<generated>"
            />
        </head>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <AppProvider>
                <StoreProvider>
                    {children}
                </StoreProvider>
            </AppProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
